services:

  backend:
    build:
      context: ./
      dockerfile: infra/docker/backend.Dockerfile

    env_file:
      - .env

    ports:
      - "8000:8000"

    networks:
      - app-network

  frontend:
    build:
      context: ./
      dockerfile: infra/docker/frontend.Dockerfile

    ports:
      - "8080:80"

    networks:
      - app-network

    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
